N_PLAYERS = 5
N_IMPOSTORS = 1
N_CREWMATES = 4

GRID_WIDTH = 40
GRID_HEIGHT = 31

MAX_STEPS = 3000
VOTING_INTERVAL = 200
VOTING_DURATION = 25

INVENTORY_CAPACITY = 2
FUEL_REQUIRED = 40

FREEZE_COOLDOWN = 50
FREEZE_RANGE_FORWARD = 2
FREEZE_WIDTH = 1

# Observations
OBS_RGB = (88, 88, 3)
FOV_SIZE = (11, 11)

PLAYERS = list(range(N_PLAYERS))
